import React, { useState, useEffect } from "react";
import { FaEdit, FaTrash } from "react-icons/fa";
import axios from "axios";
import { FaCheckCircle, FaTimesCircle } from "react-icons/fa";
import { jwtDecode } from "jwt-decode";
import { jsPDF } from "jspdf";
import dmt_logo from "../../assets/logo-header.png"; // Replace this with your logo path
import { IoMdPrint } from "react-icons/io";

const FineHistory = () => {
  const [fines, setFines] = useState([]);

  const [message, setMessage] = useState(null);
  const [messageType, setMessageType] = useState(null);
  const messageClass =
    messageType === "error" ? "alert-danger" : "alert-success";

  const fetchFinesByIssuerEmail = async () => {
    try {
      const fetchFinesUrl = `${
        import.meta.env.VITE_API_BASE_URL
      }/get-fine-details`;
      const token = localStorage.getItem("authToken");

      const decodedToken = jwtDecode(token);

      const email = decodedToken.Email;

      const response = await axios.post(
        fetchFinesUrl,
        { issuerEmail: email },
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      if (response.status === 200) {
        const fetchedFines = response.data;
        setFines(fetchedFines);
      } else {
        setMessage("Failed to fetch fines!");
        setMessageType("error");
      }
    } catch (error) {
      setMessage(
        "Failed to fetch fines " +
          (error.response ? error.response.data : error.message)
      );
      setMessageType("error");
      console.error(
        "Failed to fetch fines:",
        error.response ? error.response.data : error.message
      );
    }
  };
  useEffect(() => {
    fetchFinesByIssuerEmail();
  }, []);

  const generateFinePDF = (fines) => {
    const doc = new jsPDF();

    const drawPageBorder = () => {
      doc.setDrawColor(0, 0, 0);
      doc.setLineWidth(1);
      doc.rect(15, 8, 180, 280);
    };

    const drawHeader = () => {
      doc.addImage(dmt_logo, "PNG", 20, 10, 170, 30);
      doc.setFontSize(20);
      const title = "List of Issued Traffic Fines";
      const titleWidth = doc.getTextWidth(title);
      const pageWidth = doc.internal.pageSize.width;
      const xPosition = (pageWidth - titleWidth) / 2;
      doc.setTextColor(0, 0, 0);
      doc.text(title, xPosition, 50);

      doc.setLineWidth(0.5);
      doc.line(20, 60, 190, 60);
    };

    const drawFooter = () => {
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text("Generated by Department of Motor Traffic System", 20, 280);
    };

    const drawFine = (fine, index, yPosition) => {
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 80);
      doc.text(`Fine ${index + 1}`, 20, yPosition);
      yPosition += 6;

      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      doc.text(`Fine ID: ${fine.fineId}`, 20, yPosition);
      yPosition += 6;
      doc.text(`Offender Name: ${fine.offenderName}`, 20, yPosition);
      yPosition += 6;
      doc.text(`Issuer Name: ${fine.issuerName}`, 20, yPosition);
      yPosition += 6;
      doc.text(`Badge Number: ${fine.badgeNumber}`, 20, yPosition);
      yPosition += 6;
      doc.text(`Vehicle Number: ${fine.vehicleNumber}`, 20, yPosition);
      yPosition += 6;
      doc.text(
        `Violation Date: ${new Date(fine.violationDate).toLocaleDateString()}`,
        20,
        yPosition
      );
      yPosition += 6;
      doc.text(`Provision: ${fine.provision}`, 20, yPosition);
      yPosition += 6;
      doc.text(`Section of Act: ${fine.sectionOfAct}`, 20, yPosition);
      yPosition += 6;
      doc.text(`Court Name: ${fine.courtName}`, 20, yPosition);
      yPosition += 6;
      doc.text(
        `Due Date: ${new Date(fine.dueDate).toLocaleDateString()}`,
        20,
        yPosition
      );
      yPosition += 6;
      doc.text(`Fine Amount: Rs. ${fine.amount}`, 20, yPosition);
      yPosition += 6;
      doc.text(`Deducted Points: ${fine.deductedPoints}`, 20, yPosition);
      yPosition += 6;
      doc.text(`Station Name: ${fine.stationName}`, 20, yPosition);
      yPosition += 6;
      doc.text(`Status: ${fine.status}`, 20, yPosition);
      yPosition += 6;
      doc.text(`Location: ${fine.latitude}, ${fine.longitude}`, 20, yPosition);
      yPosition += 6;

      // Draw separator line
      doc.setLineWidth(0.3);
      doc.setDrawColor(150, 150, 150);
      doc.line(20, yPosition, 190, yPosition);
      yPosition += 10;

      return yPosition;
    };

    drawPageBorder();
    drawHeader();

    let yPosition = 70;
    let finesOnPage = 0;

    fines.forEach((fine, index) => {
      if (finesOnPage === 2) {
        // after 2 fines, add new page
        drawFooter();
        doc.addPage();
        drawPageBorder();
        drawHeader();
        yPosition = 70;
        finesOnPage = 0;
      }

      yPosition = drawFine(fine, index, yPosition);
      finesOnPage++;
    });

    drawFooter();
    doc.save("traffic_fines_report.pdf");
  };

  return (
    <>
      {/* Message Display Section */}
      {message && (
        <div
          className={`alert ${messageClass} alert-dismissible fade show w-100 w-md-50 shadow-lg rounded start-50 translate-middle-x mt-4`}
          role="alert"
        >
          <div className="d-flex align-items-center">
            {messageClass === "alert-success" && (
              <FaCheckCircle className="me-2" />
            )}
            {messageClass === "alert-danger" && (
              <FaTimesCircle className="me-2" />
            )}
            <span>{message}</span>
          </div>

          <button
            type="button"
            className="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"
            onClick={() => {
              setMessage(null);
              setMessageType(null);
            }}
          ></button>
        </div>
      )}

      <div className="container ">
        <div className="mb-2 d-flex align-items-center justify-content-end">
          <button
            className="btn custom-print-button d-flex align-items-center"
            onClick={() => generateFinePDF(fines)}
          >
            <IoMdPrint className="me-2" style={{ fontSize: "20px" }} />
            <span className="print-text">Print Report</span>
          </button>
        </div>
        {/* Search Bar */}

        <div className="d-flex flex-column gap-3">
          {fines.length > 0 ? (
            fines.map((fine) => {
              return (
                <div
                  className="card shadow-lg rounded-3 p-1"
                  style={{ borderLeft: "5px solid #55798f" }}
                  key={fine.fineId}
                >
                  <div className="card-body">
                    <div className="row justify-content-between align-items-center w-100 ">
                      <div className="col-9 ">
                        <h5 className="card-title fs-6 text-muted text-start mb-1 ">
                          {fine.provision + " "}({fine.sectionOfAct})
                        </h5>
                      </div>

                      {/* Button Section */}
                      <div className="col-3 d-flex gap-2 ">
                        {fine.status === "Paid" ? (
                          <div className=" paid-fine-details-btn px-3 border border-success">
                            <span
                              className="status-text paid-fine-details-btn-span text-success"
                              style={{
                                alignItems: "center",
                                fontSize: "14px",
                              }}
                            >
                              Paid
                            </span>
                          </div>
                        ) : (
                          <div className=" pending-fine-details-btn px-2 border border-warning">
                            <span
                              className="status-text "
                              style={{
                                color: " #b8860b",
                                alignItems: "center",
                                fontSize: "14px",
                              }}
                            >
                              Pending
                            </span>
                          </div>
                        )}

                        <div className=" points-btn  px-2 border border-success">
                          <span
                            className="status-text "
                            style={{
                              color: " #155724",
                              alignItems: "center",
                              fontSize: "14px",
                            }}
                          >
                            {fine.deductedPoints} Points
                          </span>
                        </div>
                      </div>
                    </div>

                    <h6
                      className="card-subtitle mb-3 text-muted text-start"
                      style={{ color: "#555", fontSize: "14px" }}
                    >
                      Fine Amount:{" "}
                      <span className="text-danger">{fine.amount} LKR</span>
                    </h6>

                    <div
                      className="text-start row "
                      style={{ color: "#555", fontSize: "14px" }}
                    >
                      <div className="col-6">
                        <p className="text-start mb-0">
                          <span className="fw-bold"> Offender:</span>
                          {fine.offenderName}
                        </p>
                        <p className="text-start mb-0">
                          <span className="fw-bold">Issuer:</span>{" "}
                          {fine.issuerName} ({fine.badgeNumber})
                        </p>
                        <p className="mb-0">
                          <span className="fw-bold">Violation Date:</span>{" "}
                          {
                            new Date(fine.violationDate)
                              .toISOString()
                              .split("T")[0]
                          }
                        </p>
                        <p className="mb-0">
                          <span className="fw-bold">Due Date:</span>{" "}
                          {new Date(fine.dueDate).toISOString().split("T")[0]}
                        </p>
                      </div>
                      <div className="col-6">
                        <p className="text-start mb-0">
                          <span className="fw-bold"> Vehicle Number:</span>{" "}
                          {fine.vehicleNumber}
                        </p>
                        <p className="text-start mb-0">
                          <span className="fw-bold">Station:</span>{" "}
                          {fine.stationName}
                        </p>
                        <p className="mb-0">
                          <span className="fw-bold">Court:</span>{" "}
                          {fine.courtName}
                        </p>
                        <p className="mb-0">
                          <span className="fw-bold">Status:</span> {fine.status}
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })
          ) : (
            <p>No fines found</p>
          )}
        </div>
      </div>
    </>
  );
};

export default FineHistory;
